# Generated by Django 2.0.5 on 2018-05-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoScore', '0002_auto_20180522_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
