# Generated by Django 2.0.5 on 2018-05-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoScore', '0003_video_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='score',
        ),
        migrations.AddField(
            model_name='theme',
            name='score',
            field=models.BigIntegerField(default=0),
        ),
    ]
